// import type { Metadata } from 'next';
// import "./globals.css";
// import { Poppins } from "next/font/google";
// import {
//   ClerkProvider,
//   SignedIn,
//   SignedOut,
//   SignInButton,
//   UserButton,
// } from '@clerk/nextjs';
// const poppins = Poppins({
//   subsets: ['latin'], // Specify subsets like 'latin' or 'cyrillic'
//   weight: ['300', '400', '500', '600', '700'], // Specify weights as needed
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider routerPush={() => {}} routerReplace={() => {}}>
//       <html lang="en" className="">
//         <body>
//           <SignedOut>
//             <SignInButton />
//           </SignedOut>
//           <SignedIn>
//             <UserButton />
//           </SignedIn>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
//!
import type { Metadata } from 'next';
import "./globals.css";
import { Poppins } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from '../../node_modules/@clerk/nextjs/dist/types';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={`${poppins.className}antialiased`}>
        
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
