
import type { Metadata } from 'next';
import "./globals.css";
import { Poppins } from "next/font/google";

import { ClerkProvider} from '@clerk/nextjs'
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.className}antialiased`}>
        
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
